"""add shopping categories table

Revision ID: 7f3b6862d705
Revises: 
Create Date: 2026-02-17 13:35:17.135504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3b6862d705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )

    # Standardkategorien einfuegen
    categories_table = sa.table(
        'shopping_categories',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('color', sa.String),
        sa.column('position', sa.Integer),
    )
    op.bulk_insert(categories_table, [
        {'name': 'Lebensmittel', 'slug': 'lebensmittel', 'color': '#28a745', 'position': 1},
        {'name': 'Haushalt', 'slug': 'haushalt', 'color': '#007bff', 'position': 2},
        {'name': 'Drogerie', 'slug': 'drogerie', 'color': '#e83e8c', 'position': 3},
        {'name': 'Sonstiges', 'slug': 'sonstiges', 'color': '#6c757d', 'position': 4},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_categories')
    # ### end Alembic commands ###
