"""add task categories and remove priority

Revision ID: 8985152139cb
Revises: 7f3b6862d705
Create Date: 2026-02-17 13:50:03.141945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8985152139cb'
down_revision = '7f3b6862d705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_category_id', 'task_categories', ['category_id'], ['id'])
        batch_op.drop_column('priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('fk_tasks_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('task_categories')
    # ### end Alembic commands ###
