"""add overdue_reminders_enabled to users

Revision ID: a968675a101b
Revises: 8985152139cb
Create Date: 2026-02-17 16:17:43.702977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a968675a101b'
down_revision = '8985152139cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue_reminders_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('overdue_reminders_enabled')

    # ### end Alembic commands ###
